name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonar-check:
    name: Sonar Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
        shell: pwsh
          
      - name: SonarScanner Begin
        run: |
          dotnet sonarscanner begin `
            /k:"8540675-star_NetSdrClient" `
            /o:"8540675-star" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io"
        shell: pwsh
        env:
          DOTNET_ROOT: ${{ env.DOTNET_ROOT }}
        
      - name: Build
        run: dotnet build NetSdrClientApp/NetSdrClientApp.csproj -c Release
        
      - name: SonarScanner End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        shell: pwsh
        env:
          DOTNET_ROOT: ${{ env.DOTNET_ROOT }}
